### ISSUE TITLE
Pico vs Pico-w

### ISSUE THREAD

**Issue by qbnil** [AleksaMCode/WiFi-password-stealer#4]
Hey, first of all thx for all the effort you made, been lookin for smth like that for a while, is there actually a difference if i buy either pico or pico with wireless support?

**Comment by AleksaMCode** [comment]
Thank you, I'm glad you've found this project useful. You can use this with both, the RPi Pico and the RPi Pico W. However, the process of creating a Pico-Ducky is a bit different, but everything is well documented on the pico-ducky [repo](https://github.com/dbisu/pico-ducky).

**Comment by qbnil** [comment]
alr, appreciate that
